name: Backup Databases

on:
  push:
    branches:
      - main

jobs:
  backup-databases:
    runs-on: ubuntu-latest

    steps:
      - name: Backup Databses
        uses: finer-vision/backup-databases@v0.0.32
        with:
          DB_USER: ${{ secrets.UAT_DB_USER }}
          DB_PASSWORD: ${{ secrets.UAT_DB_PASSWORD }}
          DATABASE: ("employees")
          DB_HOST: ${{ secrets.UAT_DB_HOST }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_FOLDER: ${{ secrets.UAT_S3_FOLDER }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
